---
version: '3.6'
services:
  api:
    build: .
    image: tarpaulin-api
    restart: always
    ports:
      - 8000:8000
    env_file: global.env
    environment:
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
  mysql:
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    env_file: global.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
volumes:
  mysql-data:
    name: tarpaulin-mysql-data