---
version: '3.3'
services:
  api:
    build: .
    image: tarpaulin-api
    restart: always
    ports:
      - 8000:8000
    env_file: global.env
    environment:
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      REDIS_PORT: 6379
      REDIS_HOST: redis
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    env_file: global.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  redis:
    image: redis:latest
    restart: always
    
volumes:
  mysql-data:
